### ISSUE TITLE
Which file should I start for running the program?

### ISSUE THREAD

**Issue by wangchuan** [TeamHG-Memex/decaptcha#1]

**Comment by lopuhin** [comment]
Please see an example here https://github.com/TeamHG-Memex/decaptcha/tree/master/decaptcha_example/decaptcha_example - this library is intended to be used with ``scrapy`` (scrapy.readthedocs.org).
Note that there is no captcha solving here: the library is for integrating a scrapy spider with an external captcha solver, like deathbycaptcha.
